apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gatekeeper
  namespace: argo
spec:
  project: default
  source:
    repoURL: https://open-policy-agent.github.io/gatekeeper/charts
    chart: gatekeeper
    targetRevision: 3.18.2
    helm:
      valuesObject:
        replicas: 1
        controllerManager:
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
  destination:
    namespace: gatekeeper-system
    name: in-cluster
  syncPolicy:
    syncOptions:
      - CreateNamespace=true

